#!/usr/bin/env julia
# Generic runner for the problem defined in problem.jl.
#
# Do NOT edit this file to adapt the template to a new problem -- edit
# problem.jl instead. This script only depends on the problem interface
# (core/base_problem.jl) and the `Problem` alias plus `PARAM_RANGES`
# exported by problem.jl, so it stays correct across any problem you plug in.
#
# Usage:
#     julia --project=. main.jl                            # sweep PARAM_RANGES
#     julia --project=. main.jl --params '{"n_items": 8, "capacity": 30}' --repeats 5
#     julia --project=. main.jl --time-limit 30 --gap-rel 0.01 --threads 4
#
# Repeats re-solve the same parameter combination multiple times (useful to
# measure solve-time variance). If your problem is randomized via a seed
# constructor kwarg, include "seed" in PARAM_RANGES yourself to sweep over
# distinct random instances instead.
using JSON

include("core/base_problem.jl")
include("problem.jl")

mutable struct CliArgs
    params::Union{Nothing,Dict{String,Any}}
    repeats::Int
    time_limit::Union{Nothing,Float64}
    gap_rel::Union{Nothing,Float64}
    threads::Union{Nothing,Int}
    log::String
    msg::Bool
    out::String
end

const HELP = """
Usage:
    julia --project=. main.jl [options]

Options:
    --params JSON      JSON dict for a single run, overrides the PARAM_RANGES
                       sweep, e.g. '{"n_items": 8, "capacity": 30}'
    --repeats N        Repetitions per parameter combination (default: 1)
    --time-limit S     Solver time limit (seconds)
    --gap-rel F        Solver relative MIP gap
    --threads N        Solver thread count
    --log LEVEL        info (default), debug, or silent
    --msg              Show solver output
    --out PATH         Output CSV path (default: results.csv)
"""

function parse_args(args)
    cli = CliArgs(nothing, 1, nothing, nothing, nothing, "info", false, "results.csv")
    i = 1
    while i <= length(args)
        arg = args[i]
        if arg == "--params"
            cli.params = JSON.parse(args[i + 1]); i += 2
        elseif arg == "--repeats"
            cli.repeats = parse(Int, args[i + 1]); i += 2
        elseif arg == "--time-limit"
            cli.time_limit = parse(Float64, args[i + 1]); i += 2
        elseif arg == "--gap-rel"
            cli.gap_rel = parse(Float64, args[i + 1]); i += 2
        elseif arg == "--threads"
            cli.threads = parse(Int, args[i + 1]); i += 2
        elseif arg == "--log"
            level = args[i + 1]
            level in ("info", "debug", "silent") || error("--log must be one of: info, debug, silent")
            cli.log = level; i += 2
        elseif arg == "--msg"
            cli.msg = true; i += 1
        elseif arg == "--out"
            cli.out = args[i + 1]; i += 2
        elseif arg in ("-h", "--help")
            print(HELP)
            exit(0)
        else
            error("Unknown argument: $arg")
        end
    end
    return cli
end

function param_combinations(params_override)
    params_override !== nothing && return [params_override]
    ranges = PARAM_RANGES
    isempty(ranges) && return [Dict{String,Any}()]
    rkeys = collect(keys(ranges))
    combos = Dict{String,Any}[]
    for combo in Iterators.product((ranges[k] for k in rkeys)...)
        push!(combos, Dict{String,Any}(k => v for (k, v) in zip(rkeys, combo)))
    end
    return combos
end

function csv_escape(value)
    s = string(value)
    occursin(r"[,\"\n]", s) ? "\"" * replace(s, "\"" => "\"\"") * "\"" : s
end

function write_csv(path, rows, order)
    open(path, "w") do io
        println(io, join(order, ","))
        for row in rows
            println(io, join((csv_escape(row[k]) for k in order), ","))
        end
    end
end

function main(args = ARGS)
    cli = parse_args(args)
    configure_logging(cli.log)
    silent = cli.log == "silent"
    rows = Dict{String,Any}[]

    for combo in param_combinations(cli.params)
        for rep in 1:cli.repeats
            problem = Problem(; (Symbol(k) => v for (k, v) in combo)...)
            solve!(problem; msg = cli.msg, time_limit = cli.time_limit,
                   gap_rel = cli.gap_rel, threads = cli.threads)
            row = result(problem)
            row["rep"] = rep - 1
            push!(rows, row)
            silent || @info JSON.json(row)
        end
    end

    if !isempty(rows)
        write_csv(cli.out, rows, sort!(collect(keys(rows[1]))))
        silent || @info "Wrote $(length(rows)) rows to $(cli.out)"
    end
end

if abspath(PROGRAM_FILE) == @__FILE__
    main(ARGS)
end
