#!/usr/bin/env julia
# Generic runner for the problem defined in problem.jl.
#
# Do NOT edit this file to adapt the template to a new problem -- edit
# problem.jl instead. This script only depends on the problem interface
# (core/base_problem.jl) and the `Problem` alias plus `PARAM_RANGES`
# exported by problem.jl, so it stays correct across any problem you plug in.
#
# Usage:
#     julia --project=. main.jl                                     # sweep PARAM_RANGES
#     julia --project=. main.jl --range 1:10                        # range of combinations
#     julia --project=. main.jl --rank 0 --num-ranks 4              # rank partitioning
#     julia --project=. main.jl --format sqlite --out results.db    # SQLite output
#     julia --project=. main.jl --params '{"n_items": 8}' --repeats 5
#     julia --project=. main.jl --time-limit 30 --gap-rel 0.01 --threads 4
#
using JSON

include("core/base_problem.jl")
include("problem.jl")

mutable struct CliArgs
    params::Union{Nothing,Dict{String,Any}}
    repeats::Int
    time_limit::Union{Nothing,Float64}
    gap_rel::Union{Nothing,Float64}
    threads::Union{Nothing,Int}
    log::String
    msg::Bool
    out::String
    range::Union{Nothing,UnitRange{Int}}
    rank::Union{Nothing,Int}
    num_ranks::Union{Nothing,Int}
    use_mpi::Bool
    format::String
end

const HELP = """
Usage:
    julia --project=. main.jl [options]

Options:
    --params JSON       JSON dict for a single run, overrides the PARAM_RANGES
                        sweep, e.g. '{"n_items": 8, "capacity": 30}'
    --repeats N         Repetitions per parameter combination (default: 1)
    --time-limit S      Solver time limit (seconds)
    --gap-rel F         Solver relative MIP gap
    --threads N         Solver thread count
    --log LEVEL         info (default), debug, or silent
    --msg               Show solver output
    --range START:END   1-indexed range of parameter combinations (e.g. 1:10)
    --rank R            0-indexed rank of this worker node
    --num-ranks N       Total number of worker nodes
    --use-mpi           Enable MPI execution mode via MPI.jl
    --format FORMAT     Output format: sqlite (default), json, jsonl, or csv
    --out PATH          Output path (default: results.db or results.json)
"""

function parse_range(str::String)
    parts = split(replace(str, "-" => ":"), ":")
    length(parts) == 2 || error("Invalid range format '$str', expected START:END")
    s = parse(Int, parts[1])
    e = parse(Int, parts[2])
    return s:e
end

function parse_args(args)
    cli = CliArgs(nothing, 1, nothing, nothing, nothing, "info", false, "results.db", nothing, nothing, nothing, false, "sqlite")
    i = 1
    while i <= length(args)
        arg = args[i]
        if arg == "--params"
            cli.params = JSON.parse(args[i + 1]); i += 2
        elseif arg == "--repeats"
            cli.repeats = parse(Int, args[i + 1]); i += 2
        elseif arg == "--time-limit"
            cli.time_limit = parse(Float64, args[i + 1]); i += 2
        elseif arg == "--gap-rel"
            cli.gap_rel = parse(Float64, args[i + 1]); i += 2
        elseif arg == "--threads"
            cli.threads = parse(Int, args[i + 1]); i += 2
        elseif arg == "--log"
            level = args[i + 1]
            level in ("info", "debug", "silent") || error("--log must be one of: info, debug, silent")
            cli.log = level; i += 2
        elseif arg == "--msg"
            cli.msg = true; i += 1
        elseif arg == "--range"
            cli.range = parse_range(args[i + 1]); i += 2
        elseif arg == "--rank"
            cli.rank = parse(Int, args[i + 1]); i += 2
        elseif arg == "--num-ranks"
            cli.num_ranks = parse(Int, args[i + 1]); i += 2
        elseif arg == "--use-mpi"
            cli.use_mpi = true; i += 1
        elseif arg == "--format"
            fmt = lowercase(args[i + 1])
            fmt in ("sqlite", "json", "jsonl", "csv") || error("--format must be one of: sqlite, json, jsonl, csv")
            cli.format = fmt; i += 2
        elseif arg == "--out"
            cli.out = args[i + 1]; i += 2
        elseif arg in ("-h", "--help")
            print(HELP)
            exit(0)
        else
            error("Unknown argument: $arg")
        end
    end

    if cli.out == "results.db" && cli.format != "sqlite"
        if cli.format == "json"
            cli.out = "results.json"
        elseif cli.format == "jsonl"
            cli.out = "results.jsonl"
        elseif cli.format == "csv"
            cli.out = "results.csv"
        end
    end

    return cli
end

function param_combinations(params_override)
    params_override !== nothing && return [params_override]
    ranges = PARAM_RANGES
    isempty(ranges) && return [Dict{String,Any}()]
    rkeys = sort(collect(keys(ranges)))
    combos = Dict{String,Any}[]
    for combo in Iterators.product((ranges[k] for k in rkeys)...)
        push!(combos, Dict{String,Any}(k => v for (k, v) in zip(rkeys, combo)))
    end
    return combos
end

function csv_escape(value)
    s = string(value)
    occursin(r"[,\"\n]", s) ? "\"" * replace(s, "\"" => "\"\"") * "\"" : s
end

function write_csv(path, rows, order)
    open(path, "w") do io
        println(io, join(order, ","))
        for row in rows
            println(io, join((csv_escape(row[k]) for k in order), ","))
        end
    end
end

function main(args = ARGS)
    cli = parse_args(args)
    configure_logging(cli.log)
    silent = cli.log == "silent"
    rows = Dict{String,Any}[]

    rank = 0
    num_ranks = 1

    if cli.use_mpi
        comm, rank, num_ranks = init_mpi_context()
        silent || @info "MPI initialized: rank $rank/$num_ranks"
    elseif cli.rank !== nothing && cli.num_ranks !== nothing
        rank = cli.rank
        num_ranks = cli.num_ranks
    else
        rank, num_ranks, env_name = detect_environment_rank()
        if env_name != "standalone"
            silent || @info "Auto-detected rank $rank/$num_ranks from $env_name"
        end
    end

    combos = Dict{String,Any}[]
    if cli.params !== nothing
        combos = [cli.params]
    elseif cli.range !== nothing
        N_total = total_combinations(PARAM_RANGES)
        r_start = max(1, first(cli.range))
        r_end = min(N_total, last(cli.range))
        combos = [combo_at(PARAM_RANGES, idx) for idx in r_start:r_end]
    elseif num_ranks > 1
        N_total = total_combinations(PARAM_RANGES)
        assigned_range = partition_range(N_total, rank, num_ranks)
        combos = [combo_at(PARAM_RANGES, idx) for idx in assigned_range]
    else
        combos = param_combinations(nothing)
    end

    db = cli.format == "sqlite" ? init_sqlite_db(cli.out) : nothing

    for combo in combos
        for rep in 1:cli.repeats
            problem = Problem(; (Symbol(k) => v for (k, v) in combo)...)
            solve!(problem; msg = cli.msg, time_limit = cli.time_limit,
                   gap_rel = cli.gap_rel, threads = cli.threads)
            row = result(problem)
            row["rep"] = rep - 1
            row["rank"] = rank
            push!(rows, row)

            if db !== nothing
                write_sqlite_row(db, rank, rep - 1, row)
            end
            silent || @info JSON.json(row)
        end
    end

    if !isempty(rows)
        summary = compute_summary(rows)
        if cli.format == "json"
            write_json_results(cli.out, rows, summary)
        elseif cli.format == "jsonl"
            write_jsonl_results(cli.out, rows)
        elseif cli.format == "csv"
            write_csv(cli.out, rows, sort!(collect(keys(rows[1]))))
        end
        silent || @info "Wrote $(length(rows)) rows to $(cli.out) (format: $(cli.format))"
    end
end

if abspath(PROGRAM_FILE) == @__FILE__
    main(ARGS)
end
